### ISSUE TITLE
Add ARIA support

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/html#7]
This is out of scope for me right now, but it's important it's done. If someone wants to do this, please feel free to pop into this issue and claim an item from the list. Once all items in the list have been completed, we should have ARIA support in the `html` crate.

Probably the trickiest is creating the right format for the various roles; but I suspect that should be doable by creating a `role` attribute, marking the type as `enumerable` and having it contain a vec of strings. We can unpack that to be: "this attribute takes these strings".

## Work Items

- [x] fetch the Aria spec via `xtask fetch`, and check it into `resources/standards/aria.html`
- [x] scrape the Aria spec via `xtask scrape`, and check the individually scraped attributes into `resources/scraped/aria/*.json`
- [x] parse the Aria spec via `xtask parse`, and check the normalized attributes into `resources/parsed/aria/*.json`
- [ ] merge `aria` spec into the final merged document via `xtask merge`, and check in the new attributes into `resources/merged/*.json`
- [ ] codegen the aria attributes via `xtask generate`, updating the generated output of both `crates/html-sys` and `crates/html`

**Comment by alexmoon** [comment]
I'm interested in helping to get this done. I've opened #66 to add the scraping step. Parsing should be straightforward. I may need some guidance when it comes to the `merge` and `generate` steps in how you'd like these attributes to work.

ARIA generally constrains the allowable properties based on the ARIA role of an element. The allowed roles for an element can also be constrained by the role(s) of its ancestors (and the `aria-owns` property can break the tree structure entirely). We could enforce the property constraints by creating some sort of ARIA role object that includes its properties that would be added to an element at once. I don't know a good way of constraining the allowed roles based on the roles of its ancestors.

We may also need to make use of the implicit roles of HTML elements as defined in https://w3c.github.io/html-aria/#docconformance, which would require additional scraping.

**Comment by alexmoon** [comment]
Having thought about this a bit more, we should probably just add all the ARIA properties and states that are allowed under a union of the allowed roles for a given HTML element as attributes to that element and not try to do any context-dependent restrictions.

**Comment by yoshuawuyts** [comment]
@alexmoon thank you for working on this! - I just review the first PR you made, and it looks great. I'm excited for this to be making progress!

**Comment by alexmoon** [comment]
I've created draft PRs for the remaining tasks. Not sure if you want to merge them one-by-one or all at once. Just let me know.

One note for future reference: ARIA property types include the ones already supported for attributes, plus `Identifier` and `Enumeration` which have stub implementations in `AttributeType`, plus "ID reference list" and "Token list" which are essentially `Vec`s of `Identifier`s and `Enumeration`s (respectively). It might be useful in the future to add a `Vec` `AttributeType` as well. For now, I've just made them all `String`s.
